services:

  pensionat-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: pensionat_db
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -p$DB_PASSWORD -e 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 300s

  pensionat-app:
    build: .
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://pensionat-db:3306/pensionat_db
      CUSTOMER_SERVICE_BASE_URL: http://customer-service:8081
    depends_on:
      pensionat-db:
        condition: service_healthy
